#!/usr/bin/env bash
#
# Run ONE dedicated instance -- AppHost B, for one tenant -- so that several can run at once.
#
# Phase 2 made one AppHost B serve any tenant by MERCATUS_TENANT_SLUG. Phase 3 wanted two of them
# at the same time and found the wall, which is not in this repo at all: the Aspire CLI treats a
# running AppHost as a SINGLETON keyed on the path of its apphost file, and says so itself --
#
#   "A running instance of this AppHost was found and will be stopped. To run multiple isolated
#    instances simultaneously, run from different directories such as git worktree directories."
#
# -- so a second `aspire run` on aspire/AppHostB/apphost.cs stops the first, `--isolated` and all.
# `--isolated` is still required (it randomises the CLI's own dashboard/OTLP/resource-service
# ports, the three fixed numbers in apphost.run.json); it simply is not sufficient.
#
# So each instance gets a DIRECTORY of its own, generated here from the one apphost.cs and thrown
# away by `git clean`. It is a build artifact, not a second copy to keep in step: it is rewritten
# on every run, it is gitignored, and editing it is pointless because the next run overwrites it.
#
#   - `aspire/AppHostB-<slug>/`, a SIBLING of AppHostB, because apphost.cs reaches the repo root
#     with a relative `../..` and a directory at another depth would resolve it somewhere else.
#   - a SYMLINK is not enough, twice over: the CLI resolves it back to the canonical path and
#     stops the running instance anyway, and `dotnet run --file` keys its build directory on the
#     file's CONTENT, so two byte-identical apphosts share one compiled output and the second
#     run tears down the first one's binary. The generated copy therefore ends with a line naming
#     its tenant -- that one comment is what makes it a different application to build.
#
# Usage:
#   aspire/scripts/run-dedicated.sh <slug> [bootstrap-token]
#
# The bootstrap token may also come from MERCATUS_BOOTSTRAP_TOKEN. Without either, apphost.cs
# falls back to the development literal seeded for that slug, which is what the everyday zenith
# loop uses. Mint a real one with:
#
#   curl -sX POST $PLATFORM/installations -H "authorization: Bearer $OPERATOR_TOKEN" \
#        -H 'content-type: application/json' \
#        -d '{"tenantSlug":"<slug>","expectedHost":"localhost"}'
#
# Stop it with aspire/scripts/stop-dedicated.sh <slug>.
set -euo pipefail

slug=${1:-}
token=${2:-${MERCATUS_BOOTSTRAP_TOKEN:-}}

if [[ -z "$slug" ]]; then
  echo "usage: $0 <tenant-slug> [bootstrap-token]" >&2
  exit 2
fi
# The same rule apphost.cs enforces, applied before the slug becomes a directory name here.
if [[ ! "$slug" =~ ^[a-z][a-z0-9-]{1,38}$ ]]; then
  echo "'$slug' is not a tenant slug: lower-case, starts with a letter, letters/digits/hyphens, 2-39 characters." >&2
  exit 2
fi

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source_dir="$here/../AppHostB"
run_dir="$here/../AppHostB-$slug"

mkdir -p "$run_dir"
{
  cat "$source_dir/apphost.cs"
  echo
  echo "// GENERATED by aspire/scripts/run-dedicated.sh for tenant '$slug'. Edit aspire/AppHostB/apphost.cs."
} > "$run_dir/apphost.cs"
cp "$source_dir/apphost.run.json" "$run_dir/apphost.run.json"
cp "$source_dir/aspire.config.json" "$run_dir/aspire.config.json"

cd "$run_dir"
export MERCATUS_TENANT_SLUG="$slug"
[[ -n "$token" ]] && export MERCATUS_BOOTSTRAP_TOKEN="$token"
exec aspire run --isolated --detach --non-interactive --nologo --format Json
