/**
 * Generates Traefik's dynamic configuration from the ports Aspire assigned.
 *
 * The routing table is fixed -- one hostname per surface, the store API as the lowest-priority
 * catch-all -- but the backends behind it are no longer on literal ports, so this file used to be
 * a checked-in `dynamic.yml` full of numbers that only held while §8.1's table did. It is written
 * at run time instead, from the same EndpointReferences every other resource is configured with,
 * and Traefik's file provider picks it up with `--providers.file.watch=true`.
 *
 * Every backend is a process on the HOST, so each server URL goes through host.docker.internal --
 * which the AppHost maps to the docker host gateway. That rewrite is the whole reason this is a
 * generator and not a straight copy: Aspire hands over `http://127.0.0.1:<port>`, and 127.0.0.1
 * inside the container is the container.
 *
 * The store router stays a catch-all at the lowest priority on purpose. Tenant resolution takes a
 * REQUEST, not a route parameter (3.6): `acme.localtest.me` and `/t/acme` are both valid ways to
 * name a tenant to the API, and the edge must not decide which one is allowed. That is also why
 * the storefront gets a name of its own rather than stealing `acme.localtest.me`, which the API
 * resolves host-first.
 *
 *   MERCATUS_EDGE_OUT   where to write the YAML, relative to cwd
 *   MERCATUS_EP_*       the backends, as written by write-stack-manifest.mjs's contract
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

/** router name -> [hostname, the MERCATUS_EP_* key behind it]. Order is the file's order. */
const SURFACES = [
  ['platform', 'platform.localtest.me', 'platform'],
  ['bank', 'bank.localtest.me', 'bank'],
  ['storefront', 'shop.localtest.me', 'storefront'],
  ['dashboard', 'dash.localtest.me', 'dashboard'],
  ['admin', 'console.localtest.me', 'admin'],
  ['store-api', 'api.localtest.me', 'store_pooled'],
];

const out = process.env.MERCATUS_EDGE_OUT;
if (!out) {
  console.error('MERCATUS_EDGE_OUT is not set -- nothing to write.');
  process.exit(1);
}

/**
 * Aspire gives us a loopback URL. Traefik dials it from inside its container, where loopback is
 * the container itself, so the host has to be rewritten and the port carried across untouched.
 */
function fromInsideTheContainer(key) {
  const url = process.env[`MERCATUS_EP_${key.toUpperCase()}`];
  if (!url) throw new Error(`MERCATUS_EP_${key.toUpperCase()} is not set -- the edge cannot route to "${key}".`);
  const { port } = new URL(url);
  if (!port) throw new Error(`MERCATUS_EP_${key.toUpperCase()} ("${url}") carries no port.`);
  return `http://host.docker.internal:${port}`;
}

const services = new Map();
const routers = [];

for (const [router, hostname, key] of SURFACES) {
  services.set(key, fromInsideTheContainer(key));
  routers.push(
    `    ${router}:`,
    `      rule: "Host(\`${hostname}\`)"`,
    '      entryPoints: [web]',
    `      service: ${key}`,
    '      priority: 100',
  );
}

// Anything unmatched is the store API, as it has been since 8.1 -- including the bare host and
// `<tenant>.localtest.me`, both of which the API resolves for itself.
routers.push(
  '    store-pooled-catchall:',
  '      rule: "PathPrefix(`/`)"',
  '      entryPoints: [web]',
  '      service: store_pooled',
  '      priority: 1',
);

const yaml = [
  '# GENERATED by aspire/AppHostA/traefik/write-dynamic.mjs on every `aspire run`. Do not edit:',
  '# the ports below are whatever Aspire assigned this run, and an edit is lost on the next one.',
  `# Written ${new Date().toISOString()}.`,
  'http:',
  '  routers:',
  ...routers,
  '',
  '  services:',
  ...[...services].flatMap(([name, url]) => [
    `    ${name}:`,
    '      loadBalancer:',
    '        servers:',
    `          - url: "${url}"`,
  ]),
  '',
].join('\n');

const path = resolve(process.cwd(), out);
mkdirSync(dirname(path), { recursive: true });
writeFileSync(path, yaml);

console.log(`Wrote ${path}`);
for (const [name, url] of services) console.log(`  ${name.padEnd(14)} -> ${url}`);
